version: '3.8'
services:
  gateway:
    build: ./gateway
    image: gatewaytest
    container_name: gatewaytest
    ports:
      - "8080:8080"
    depends_on:
    - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: ./server
    image: servertest
    container_name: servertest
    restart: always
    ports:
      - "9090:9090"
    depends_on:
    - db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shareIt
  db:
    image: postgres:14.3
    container_name: postgres
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareIt
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=postgres